### ISSUE TITLE
SPenSdkBinding and SPen SDK 2.3

### ISSUE THREAD

**Issue by ghost** [xamarin/monodroid-samples#43]
I pulled the sample to create a monodroid-binding for the Samsung SPen SDK, but it doesn't work with the SDK 2.3.

Attached you'll find a snippet of the error messages. Anything I don't see here? I added the libspen23.jar in "Jars" as 'inputjar'.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Bindings.targets: Error: Tool exited with code: 1. Output: java.lang.NoClassDefFoundError: android/view/View$OnHoverListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at jar2xml.JavaArchive.getPackages(JavaArchive.java:86)
    at jar2xml.JavaArchive.getPackages(JavaArchive.java:64)
    at jar2xml.Start.main(Start.java:118)
Caused by: java.lang.ClassNotFoundException: android.view.View$OnHoverListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 14 more
